### ISSUE TITLE
Money duplication - via Bank [ECONOMY]

### ISSUE THREAD

**Issue by wMartyyS** [daneedev/2.C-Bot#80]
When you put a bet e.g. 200Kč in blackjack then midgame put it in bank, you wont lose any money when you lose the game, and when you win you will always ofc get the price.

**Comment by daneedev** [comment]
Fixed in https://github.com/daneedev/2.C-Bot/commit/6724b854769e8a7901948783b6894b6d26ab6310. +400 coins reward
